name: My Testing GitHub Action

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Greeting
        run: echo "Hello, GitHub Actions! \n Let Start!!!"
